
# init task == prebuild, command task == run on workspace startup
# .bundle/config sets bundle path to .gems (gitignored) so that prebuild is saved locally 
tasks:
  - name: jekyll
    init: bundle install 
    command: bundle exec jekyll serve    

# Ports to expose on workspace startup
ports:
  - port: 4000
    onOpen: open-preview
