# Commands to start on workspace startup
tasks:
  - name: jeykyll
    init: >
      bundle install &&
      gp sync-done bundle
    command: bundle exec jekyll serve
# Ports to expose on workspace startup
ports:
  - port: 4000
    onOpen: open-preview
