# Commands to start on workspace startup
tasks:
  - name: jeykyll
    init: echo " starting bundle install"
    command: bundle install 
  - name: jeykyll serve
    init: echo "starting server"
    command: bundle exec jekyll serve    
# Ports to expose on workspace startup
ports:
  - port: 4000
    onOpen: open-preview
