title:              Kraken Tips
email:              tanmaybhat24@gmail.com
description:        Blogs on DevOps, SRE and Life
author:             Tanmay Bhat
baseurl:            ""
url:                "https://tanmay-bhat.github.io"

# Social Profiles
twitter_username: tanmaybhat98
github_username: tanmay-bhat
#facebook_username: dont-click-this
#instagram_username: dont-click-this-again
linkedin_username: tanmay-bhat-024
# Add your google-analytics ID here to activate google analytics
google_analytics: "" # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
